---
- name: Self Serve Hosts
  hosts: selfserve_agents
  vars:
    action: "{{ lookup('env','action') }}"
  become: true
  user: "{{ lookup('env','MOZ_USER') | default(lookup('env', 'USER'), true) }}"
  tasks:
      - name: Stop selfserve_agents
        supervisorctl:
          name: selfserve-agent
          state: stopped
        when:
            action == "stop"

      - name: Start selfserve_agents
        supervisorctl:
          name: selfserve-agent
          state: started
        when:
            action == "start"

      - name: get status of selfserve_agents
        command: supervisorctl status selfserve-agent
        register: status
        changed_when: false
        when:
          action == "status"

      - name: Display status
        debug: msg={{ status.stdout.split('\n') }}
        when:
          action == "status"

      - name: Usage error
        fail: msg="Specify an action of start, stop, status via -e"
        when:
          - action != "start"
          - action != "stop"
          - action != "status"

